

processing file: sc_DGE_module.Rmd
  |                                                                              |                                                                      |   0%  |                                                                              |..                                                                    |   3%
  ordinary text without R code

  |                                                                              |.....                                                                 |   6%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |                                                                              |.......                                                               |  10%
  ordinary text without R code

  |                                                                              |.........                                                             |  13%
label: hpc_notes (with options) 
List of 1
 $ include: logi FALSE

  |                                                                              |...........                                                           |  16%
  ordinary text without R code

  |                                                                              |..............                                                        |  19%
label: populate_meta_data_database (with options) 
List of 3
 $ eval   : logi TRUE
 $ echo   : logi FALSE
 $ results: logi FALSE

Quitting from lines 44-581 (sc_DGE_module.Rmd) 
Error: package or namespace load failed for 'glmGamPoi' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/camp/stp/babs/working/boeings/Projects/pachnisv/song.chng/330_10xscRNAseq_DIV4_DIV11_DIV20_SC19069/basedata/Matrix/libs/Matrix.so':
  libgfortran.so.5: cannot open shared object file: No such file or directory
In addition: Warning message:
package 'glmGamPoi' was built under R version 4.0.3 

Execution halted
