

processing file: sc_Trajectory_Analysis.Rmd
  |                                                                              |                                                                      |   0%  |                                                                              |....                                                                  |   6%
  ordinary text without R code

  |                                                                              |........                                                              |  12%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |                                                                              |............                                                          |  18%
  ordinary text without R code

  |                                                                              |................                                                      |  24%
label: hpc_notes (with options) 
List of 1
 $ include: logi FALSE

  |                                                                              |.....................                                                 |  29%
  ordinary text without R code

  |                                                                              |.........................                                             |  35%
label: populate_meta_data_database (with options) 
List of 3
 $ eval   : logi TRUE
 $ echo   : symbol F
 $ results: symbol F

Skipping install of 'biologicSeqTools' from a github remote, the SHA1 (31c9c1b0) has not changed since last install.
  Use `force = TRUE` to force installation
Skipping install of 'biologicToolsSC' from a github remote, the SHA1 (c9ec492f) has not changed since last install.
  Use `force = TRUE` to force installation
  |                                                                              |.............................                                         |  41%
  ordinary text without R code

  |                                                                              |.................................                                     |  47%
label: runSlingshot (with options) 
List of 4
 $ echo   : symbol F
 $ eval   : symbol T
 $ warning: logi FALSE
 $ results: chr "asis"

Loading required package: princurve
Using full covariance matrix
Quitting from lines 157-1020 (sc_Trajectory_Analysis.Rmd) 
Error in eval(expr, envir, enclos) : 
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Execution halted
