---
output: 
    html_document:
        code_folding: hide
        df_print: tibble
        highlight: default
        theme: paper
        toc: true
        toc_depth: 5
        toc_float: true
        css: src/assets/style/style.css

always_allow_html: yes
---


```{r setup, include=FALSE}
## Load conda environment 
# conda activate R-monocle3
# R version 4.0.2

knitr::opts_chunk$set(
    tidy = F,
    tidy.opts = list(width.cutoff = 120),
    message = FALSE,
    warning = FALSE
)



#Create the environment and load a suitable version of R, e.g. so:
if (!require("remotes")){
  install.packages("remotes")
}

remotes::install_github("rstudio/renv")

if (!file.exists("renv.lock")){
    renv::init()
} else {
    renv::restore()
}

packages <- c("DESeq2")

if (!requireNamespace("BiocManager", quietly = TRUE)){
  install.packages("BiocManager")
}

BiocManager::install(setdiff(packages, rownames(installed.packages())))

renv::install("gam")
renv::install('circlize')
renv::install("bioc::ComplexHeatmap")

# if (!requireNamespace("BiocManager", quietly=TRUE))
#     install.packages("BiocManager")
# BiocManager::install("ComplexHeatmap")
                    
source("src/modules/trajectory_analyses/trajectory.helper.functions.R")                 
# devtools::install_github("decusInLabore/biologicSeqTools")
# devtools::install_github("decusInLabore/biologicToolsSC")

renv::install("decusInLabore/biologicSeqTools")
renv::install("decusInLabore/biologicToolsSC")

library(Seurat)
library(biologicSeqTools)
# library(biologicToolsSC)

# library(tidyverse)
# library(dplyr)
# library(Seurat)
# library(ggplot2)
# library(tidyr)
# library(knitr)

cwd <- paste0(here::here(),"/")
tempWorkDir <- paste0(cwd, "../")



#library(biologicToolsSC)

upload.results.to.database <- TRUE
save.chunk.intermediates <- TRUE


###############################################################################
##                                                                           ##
figureCount <- 1

## Load R module load R/3.5.1-foss-2018b ##
#setwd(Obio@parameterList$localWorkDir)




##                                                                           ##
###############################################################################




```


<!-- Running Individual Modules in R -->
<!-- For example rmarkdown::render("src/modules/settings/partB.set.parameters.Rmd", output_dir = "..") -->


<!-- Essential 1: Load data (output required later) -->
```{r child = 'src/modules/trajectory_analyses/T.0.load.data.Rmd', eval=TRUE}

```

<!-- Optional 2: Retrieve Reference Genes from Database or Gmt file -->
```{r child = 'src/modules/section_B/B.2.retrieve.reference.gene.sets.Rmd', eval=TRUE}
```

<!-- Optional 3: Diffusion map -->
```{r child = 'src/modules/trajectory_analyses/T.1.diffusion.map.Rmd', eval=FALSE}
```

<!-- Optional 4: slingshot -->
```{r child = 'src/modules/trajectory_analyses/T.2.slingshot.Rmd', eval=FALSE}
```

<!-- Optional 5: monocle3 -->
```{r child = 'src/modules/trajectory_analyses/T.3.monocle3.trajectory.module.Rmd', eval=FALSE}
```

<!-- Optional 6: ouija -->
```{r child = 'src/modules/trajectory_analyses/T.4.ouija.trajectory.module.Rmd', eval=TRUE}
```



```{r saveobject, eval=TRUE, echo=T, results=F}
### Will save Obio object here, so it can be re-used with different parameters
save(Obio, 
     file = paste0(
         Obio@parameterList$localWorkDir,
         Obio@parameterList$project_id,
         ".bioLOGIC.Robj"
     )
)

print("Obio Object saved.")

save(OsC,
    file = paste0(
         Obio@parameterList$localWorkDir,
         Obio@parameterList$project_id,
        ".Seurat.Robj"
     )
)

```



```{r create_report_params, eval=T, results="asis"}

## Try to retrieve project data from db ##
library(RMySQL)
db.pwd2 <- "zU3ufd9L"
db.user2 <- "reader"
host2 <- "clvd1-db-u-p-17.thecrick.org"
projectParams <- Obio@documentationParams

tryCatch({
    dbDB = DBI::dbConnect(
        drv = RMySQL::MySQL(), 
        user = db.user2, 
        password = db.pwd2, 
        host = host2, 
        dbname = "clarity_shadow"
    )
dfProposal =  DBI::dbGetQuery(dbDB, paste0("SELECT * FROM clarify_asf_proposals WHERE project_name ='",Obio@parameterList$lims.id,"'"))
dbDisconnect(dbDB)
  }, error = function(x) {
    message("Project Database could not be reached or has no entry in Obio@parameterList$lims.id for this analysis.")
   
})

if (exists("dfProposal")){
  if (nrow(dfProposal) == 1){
      if (!is.na(dfProposal[1,"ProjectAlias"]) & dfProposal[1,"ProjectAlias"] != ""){
          projectParams[["title"]] = paste0(dfProposal[1,"ProjectAlias"], " - ", dfProposal[1,"project_name"])
      }
      
      if (!is.na(dfProposal[1,"project_user"]) & dfProposal[1,"project_user"] != ""){
          projectParams[["subtitle"]] = paste0(dfProposal[1,"user_lab"], " Lab - ", dfProposal[1,"project_user"])
          projectParams[["subtitle"]] <- gsub("^ Lab - ", "", projectParams[["subtitle"]])
          
      }
      
      if (!is.na(dfProposal[1,"proposal_text"]) & dfProposal[1,"proposal_text"] != ""){
          projectParams[["abstract"]] = dfProposal[1,"proposal_text"]
         
          
      }
  }
}
   
## Escape all special characters
projectParams <- lapply(
  projectParams, function(x) 
  #gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\1", x)
  gsub("([.|()/\\^{}+$*?]|\\[|\\])", " ", x)
) 

projectParams <- lapply(
  projectParams, function(x) 
  #gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\1", x)
  gsub("\\\n", " ", x)
) 


#projectParams$title <- "Title"
# projectParams$abstract <- "This is the QC section."
#projectParams$subtitle <- "Abstract"

```



## Documentation
```{r documentation, eval=TRUE, echo=T, results=T}
renv::snapshot()
sessionInfo()
```

---
title: "`r projectParams$title`"
subtitle:  "Trajectory Analysis Module"
author:
    - Bioinformatics: Stefan Boeing^[The Francis Crick Institute, stefan.boeing@crick.ac.uk]
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'

abstract: |
    "This is the trajectory analysis module"


---