<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r violin_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "violin."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

# Load specific version of R
#module purge;source /camp/stp/babs/working/software/modulepath_new_software_tree_2018-08-13;module load pandoc/2.2.3.2-foss-2016b;ml R/4.0.3-foss-2020a
```



```{r data_prep_violin, echo=TRUE, eval=TRUE, warning=FALSE, results=F}

## For Violinplots we want single gene lists
## Add each cat to ref list 
## Load gene sets from cat reference file
catFN <-  Obio@parameterList$catRefFile

if (!is.null(catFN) && file.exists(catFN)){
  dfCat <- read.delim(
    catFN, 
    sep = "\t",
    stringsAsFactors = F
  )


  for (i in 1:ncol(dfCat)){
    catName <- colnames(dfCat)[i]
    geneVec <- unique(
      as.vector(
        dfCat[3:nrow(dfCat), i]
      )
    )
    geneVec <- geneVec[geneVec %in% row.names(OsC)]
    catList <- list()
    catList[[catName]] <- geneVec
    HMgeneSelections[[catName]] <- catList
  }
}
geneList <- lapply(HMgeneSelections, function(x) unique(unlist(x)))
geneList <- lapply(geneList, function(x) x[x %in% row.names(OsC)])
selVec <- unlist(lapply(geneList, function(x) length(x) != 0))
geneList <- geneList[selVec]

plotList <- list()
chnkVec <- as.vector(NULL, mode = "character")

for (i in 1:length(geneList)){
  
tag <- paste0("Vln_", names(geneList)[i])  

  geneList[[i]] <- geneList[[i]][rowSums(OsC@assays$RNA[geneList[[i]],]) != 0]
    
  if (length(geneList[[i]]) > 1 & length(geneList[[i]]) <=  50){
    
    Idents(OsC) <- "clusterName"  
    plotList[[tag]] <- Seurat::VlnPlot(
        object = OsC,
        features = geneList[[i]],
        pt.size = 1,
        stack=T,
        flip = T
    ) + ggplot2::theme(legend.position = "none"
    ) + ggplot2::ggtitle(gsub("_", " ", tag)
    ) + theme(
                axis.title.y  = element_blank(),
                axis.title.x  = element_blank()
        )  + theme(axis.text.x = element_text(size=rel(textSize), angle = 45, hjust=1))
  

  FNbase <- paste0(tag, VersionPdfExt)

  FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
  FNrel <- paste0("report_figures/", FNbase)
            
  pdf(FN)
    print(plotList[[tag]])
  dev.off()

  figLegend <- paste0(
    '**Figure ', 
    figureCount, 
    ':** ',
    'Violin plots split by cluster for gene set ',gsub("_", " ", tag),'. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>.'
  )
            
  figureCount <- figureCount + 1

  NewChnk <- paste0(
    "#### ", tag,
    "\n```{r violin_",
    tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
    figLegend,"'}\n",
    "\n",
    "\n print(plotList[['",tag,"']])",
    "\n cat(  '\n')",
    "\n\n\n```\n"   
)

  chnkVec <- c(
    chnkVec,
    NewChnk
  )
  }
}

# plotList <- addHeatmap2List(
#     OsC = OsC,
#     geneGroupList = geneGroupList,
#     relativeExpression = TRUE,
#     plotList = plotList,
#     cmdVec = NULL,
#     tag = "Channels_Rel",
#     showAllLegends = TRUE
#     )


# pdf("../../../../html_local/report_figures/stacked.violin.plots.V3.asl545.pdf")
# plotList
# dev.off()
if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}    
    
```


### Violinplots {`r tabVar`}

In this section violinplots for various gene categories are provided. 

```{r Cluster_violinplot_overview, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"}

cat(paste(knit(text = chnkVec, quiet = T), collapse = '\n'))

```