<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r create_sankey_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "B132.Areaplot."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```



```{r, echo=TRUE, eval=TRUE, warning=FALSE, results=F}


###############################################################################
## This part will allow to just render this chapter                          ##

## Set renderChapter = TRUE if you want individual chapters to be processed
if (!exists("renderChapter")){
    renderChapter <- FALSE
}

# renderChapter <- TRUE

## Load Obio biologic object and OsC single-cell object for renderByChapter mode
if (renderChapter){
      
      ## Load biologic object
      source("load.biologic.robj.R")
  
      ## Load Seurat object
      SeuratFN <- paste0(Obio@parameterList$localWorkDir,list.files(Obio@parameterList$localWorkDir)[grep(".Seurat.Robj", list.files(Obio@parameterList$localWorkDir))])
      
      load(SeuratFN)
}

## All data for this chapter loaded                                          ##
###############################################################################

plotList <- list()
chnkVec <- as.vector(NULL, mode = "character")

genotypes <- "WT"
k = 1

# for (i in 1:length(genotypes)){
 
    dfRes <- OsC@meta.data
    tag2 <- "meta_Treatment"
    
    pos <- grep(tag2, names(dfRes))
    if (length(pos) == 0){
      tag <- "sampleName"
    }
    
    selVec <- c("cellID", "clusterName", "clusterColor", tag2)
    
    labelOrder <- unique(dfRes[,tag2])
    
    # dfRes <- dfRes[dfRes$meta_Genotype == genotypes[i], selVec]
    dfRes[["timepoint"]] <- dfRes[,tag2]
    
    for (i in 1:length(labelOrder)){
      dfRes[["timepoint"]] <- gsub(labelOrder[i], i, dfRes$timepoint)
    }
    
    
    dfRes$timepoint <- as.numeric(dfRes$timepoint)
    
    
    dfCol <- unique(dfRes[,c("clusterName", "clusterColor")])
    row.names(dfCol) <- dfCol$clusterName
    dfCol <- dfCol[Obio@parameterList$clusterNameOrder, ]
    
    colVec <- dfCol$clusterColor
    names(colVec) <- dfCol$clusterName
    
    
    # Percentages
    library(dplyr)
    data <- dfRes  %>%
      group_by(timepoint, clusterName) %>%
      summarise(n = n())  %>%
      mutate(percentage = n / sum(n))
    
    
    tag <- paste0("Percent_Area_plot_", genotypes[k])
    
    data$clusterName <- factor(
        data$clusterName, 
        levels = Obio@parameterList[["clusterNameOrder"]]
    )
    
    data$clusterName <- factor(data$clusterName, levels = Obio@parameterList$clusterNameOrder)
    
    plotList[[tag]] <- ggplot2::ggplot(data, ggplot2::aes(x = timepoint, y = percentage,
                         fill = clusterName)) +
        ggplot2::geom_area() +
        ggplot2::theme_bw()  +  
        ggplot2::theme(
          axis.text.y   = ggplot2::element_text(size=8),
          axis.text.x   = ggplot2::element_text(size=8),
          axis.title.y  = ggplot2::element_text(size=8),
          axis.title.x  = ggplot2::element_text(size=8),
          axis.line = ggplot2::element_line(colour = "black"),
          panel.border = ggplot2::element_rect(colour = "black", fill=NA, size=1),
          plot.title = ggplot2::element_text(hjust = 0.5, size = 12),
          legend.title = ggplot2::element_blank()
        ) + 
        ggplot2::ggtitle(paste0("Area plot for ", genotypes[k])) +
        ggplot2::xlab(tag2) +
        ggplot2::scale_fill_manual("Clusters" ,values = colVec) +
        ggplot2::scale_x_continuous(
            breaks=c(1:length(labelOrder)), 
            labels=c(labelOrder)
        )



        FNbase <- paste0(tag, VersionPdfExt)

        FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
        FNrel <- paste0("report_figures/", FNbase)
                    
        pdf(FN)
            print(plotList[[tag]])
        dev.off()
            
          
            
        figLegend <- paste0(
                    '**Figure ', 
                    figureCount, 
                    ':** ',
                    'Area distribution plot for genotype ',genotypes[k],'. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>.'
                )
                
        figureCount <- figureCount + 1
    
        NewChnk <- paste0(
        "#### ", tag,
        "\n```{r area_",
        tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
        figLegend,"'}\n",
        "\n",
        "\n print(plotList[['",tag,"']])",
        "\n cat(  '\n')",
        "\n\n\n```\n"   
        )
    
        chnkVec <- c(
            chnkVec,
            NewChnk
        )
# }

        
###############################################################################
## Add N-cell chart                                                          ##
    
genotypes <- "WT"
k = 1

# for (i in 1:length(genotypes)){
 
        dfRes <- OsC@meta.data
    tag2 <- "meta_Treatment"
    
    pos <- grep(tag2, names(dfRes))
    if (length(pos) == 0){
      tag <- "sampleName"
    }
    
    selVec <- c("cellID", "clusterName", "clusterColor", tag2)
    
    labelOrder <- unique(dfRes[,tag2])
    
    # dfRes <- dfRes[dfRes$meta_Genotype == genotypes[i], selVec]
    dfRes[["timepoint"]] <- dfRes[,tag2]
    
    for (i in 1:length(labelOrder)){
      dfRes[["timepoint"]] <- gsub(labelOrder[i], i, dfRes$timepoint)
    }
    
    
    dfRes$timepoint <- as.numeric(dfRes$timepoint)

    
    dfCol <- unique(dfRes[,c("clusterName", "clusterColor")])
    row.names(dfCol) <- dfCol$clusterName
    dfCol <- dfCol[Obio@parameterList$clusterNameOrder, ]
    
    colVec <- dfCol$clusterColor
    names(colVec) <- dfCol$clusterName
    
    
    # Percentages
    library(dplyr)
    data <- dfRes  %>%
      group_by(timepoint, clusterName) %>%
      summarise(n = n())
    
    
    tag <- paste0("N_cells_Area_plot_", genotypes[k])
    
    data$clusterName <- factor(
        data$clusterName, 
        levels = Obio@parameterList[["clusterNameOrder"]]
    )
    
    data$clusterName <- factor(data$clusterName, levels = Obio@parameterList$clusterNameOrder)
    
    plotList[[tag]] <- ggplot2::ggplot(data, ggplot2::aes(x = timepoint, y = n,
                         fill = clusterName)) +
        ggplot2::geom_area() +
        ggplot2::theme_bw()  +  
        ggplot2::theme(
          axis.text.y   = ggplot2::element_text(size=8),
          axis.text.x   = ggplot2::element_text(size=8),
          axis.title.y  = ggplot2::element_text(size=8),
          axis.title.x  = ggplot2::element_text(size=8),
          axis.line = ggplot2::element_line(colour = "black"),
          panel.border = ggplot2::element_rect(colour = "black", fill=NA, size=1),
          plot.title = ggplot2::element_text(hjust = 0.5, size = 12),
          legend.title = ggplot2::element_blank()
        ) + 
        ggplot2::ggtitle(gsub("_", " ", tag)) + 
        ggplot2::xlab(tag2) +
        ggplot2::scale_fill_manual("Clusters" ,values = colVec) +
        ggplot2::scale_x_continuous(
            breaks=c(1:length(labelOrder)), 
            labels=c(labelOrder)
        )



        FNbase <- paste0(tag, VersionPdfExt)

        FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
        FNrel <- paste0("report_figures/", FNbase)
                    
        pdf(FN)
            print(plotList[[tag]])
        dev.off()
            
          
            
        figLegend <- paste0(
                    '**Figure ', 
                    figureCount, 
                    ':** ',
                    'Area distribution plot for genotype ',genotypes[i],'. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>.'
                )
                
        figureCount <- figureCount + 1
    
        NewChnk <- paste0(
        "#### ", tag,
        "\n```{r area_",
        tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
        figLegend,"'}\n",
        "\n",
        "\n print(plotList[['",tag,"']])",
        "\n cat(  '\n')",
        "\n\n\n```\n"   
        )
    
        chnkVec <- c(
            chnkVec,
            NewChnk
        )
# }        
            
## Done                                                                      ##
###############################################################################
        
        
            
if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}
        
        
        

```

### Area Distribution Plot {`r tabVar`}
```{r, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))


```

