<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r set_create_sample_list_parameters_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "QC.A.create.sample.list."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```

```{r create_sample_list, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"}
###############################################################################
## Create Sample List QC                                                     ## 

## Assign cell cycle scores
if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol" 
} else {
    queryGS <- Obio@parameterList$geneIDcolumn
}

s.genes <- retrieve.gene.category.from.db(
    cat_id = "ag_lab_categories__41",
    password = db.pwd,
    gene.symbol = queryGS,
    user = Obio@dbDetailList$db.user,
    host = Obio@dbDetailList$host
)

g2m.genes <- retrieve.gene.category.from.db(
    cat_id = "ag_lab_categories__42",
    password = db.pwd,
    gene.symbol = queryGS,
    user = Obio@dbDetailList$db.user,
    host = Obio@dbDetailList$host
)

#Obio@scDetailList$vars.to.regress <- c("S_Score", "G2M_Score")

if (is.null(Obio@scDetailList$vars.to.regress)){
    stringVar <- "### Regressed-out Variables /n No regression was applied to input single-cell samples before integration."
} else {
    stringVar <- paste0("### Regressed-out Variables /n Regression for parameter ", Obio@parameterList$vars.to.regress, " was used on the individual single-cell samples before integration.")
}

if (!is.null(Obio@scDetailList$vars.to.regress)){
    cat(
        paste0(
            c(
                "**Variables Regressed in UMAP Displays** \n",
                stringVar,"\n",
                paste0("- `", Obio@scDetailList$vars.to.regress, "`")
            ), 
            collapse  = " \n "
            
        )
    )
} else {
    cat(
        "** No variables regressed in main QC section **"
    )
}


SampleList <- biologicToolsSC::createSampleListQC(
    obj = Obio,
    reduce = Obio@parameterList$debugReduce,    
    vars.to.regress = Obio@scDetailList$vars.to.regress,
    s.genes = s.genes,
    g2m.genes = g2m.genes,
    annotateCellCyclePhase = TRUE
)


if (is.null(Obio@parameterList$debugReduce)){
    debugReducOutput <- "Full Dataset"
} else {
    debugReducOutput <- paste0(Obio@parameterList$debugReduce * 100, "% of all cells used.")
}

cat(paste0("Cell Recuction: ",debugReducOutput))
lapply(SampleList, dim)    
    


## Done                                                                      ##
###############################################################################

```


