<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r sample_level_QC_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "QC.A.create.sample.level.QC.plots."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```

```{r percent_mt, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##
resList <- doPercMT_plotSL(
        SampleList = SampleList,
        obj = Obio,
        figureCount = figureCount,
        VersionPdfExt = ".pdf",
        tocSubLevel = 4
)


plotListRF <- resList$plotListRF
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount

## Done create cellRanger QC plots                                           ##
###############################################################################

if (length(plotListRF) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}

```

### Create PercentMT Historgrams Plots {`r tabVar`}
```{r Plot_percentMT_hist, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```

```{r nFeature_data, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##
resList <- doRNAfeat_plotSL(
        SampleList,
        obj = Obio,
        figureCount = figureCount,
        VersionPdfExt = ".pdf",
        tocSubLevel = 4
)

plotListRF <- resList$plotListRF
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount

## Done create cellRanger QC plots                                           ##
###############################################################################

if (length(plotListRF) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}

```

### Create RNA Feature Historgrams Plots {`r tabVar`}

```{r Plot_nFeatureRNA_hist, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```


```{r UMAP_data, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##
resList <- doUMAP_plotSL(
        SampleList,
        obj = Obio,
        figureCount = figureCount,
        VersionPdfExt = ".pdf",
        tocSubLevel = 4,
        dotsize = 0.5
)

plotListSQCUMAP <- resList$plotListSQCUMAP
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount

## Done create cellRanger QC plots                                           ##
###############################################################################

if (length(plotListSQCUMAP) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}

```

### Plot UMAP Per Sample {`r tabVar`}
```{r Plot_UMAP, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))


tabVar <- ""
```


```{r UMAP_data_CC, echo=TRUE, eval=FALSE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##
resList <- doUMAP_cellCyle(
        SampleList,
        obj = Obio,
        figureCount = figureCount,
        VersionPdfExt = ".pdf",
        tocSubLevel = 4,
        dotsize = 0.5,
        cellCycleRefFile = paste0(hpc.mount, "Projects/reference_data/cell_cycle_vignette_files/nestorawa_forcellcycle_expressionMatrix.txt")
)


plotList <- resList$plotList
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount

## Done create cellRanger QC plots                                           ##
###############################################################################


if (length(plotList) > 3){
    tabVar <- "### Plot Cell Cycle UMAP Per Sample .tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- "### Plot Cell Cycle UMAP Per Sample .tabset .tabset-fade .tabset-pills"
}


```


{`r tabVar`}
```{r Plot_UMAP_CC, echo=TRUE, eval=FALSE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

tabVar <- ""
```


```{r cell_cyle_hist_data, echo=TRUE, eval=FALSE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##
resList <- doCellCycleBarchart(
        SampleList,
        obj = Obio,
        figureCount = figureCount,
        VersionPdfExt = ".pdf",
        tocSubLevel = 4,
        cellCycleRefFile = paste0(hpc.mount, "Projects/reference_data/cell_cycle_vignette_files/nestorawa_forcellcycle_expressionMatrix.txt")
)

plotList <- resList$plotList
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount

## Done create cellRanger QC plots                                           ##
###############################################################################

if (length(plotList) > 3){
    tabVar <- "### Plot Per Sample Cell Cycle Estimate .tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- "### Plot Per Sample Cell Cycle Estimate .tabset .tabset-fade .tabset-pills"
}


```


 {`r tabVar`}
```{r Plot_cellCycleBarchart, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))


if (!exists("runDoubletFinder")){
    runDoubletFinder <- TRUE
}

tabVar <- ""

```


```{r DF_data, echo=runDoubletFinder, eval=runDoubletFinder, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##
resList <-  doDF_plotSL(
        SampleList,
        obj = Obio,
        figureCount = figureCount,
        VersionPdfExt = ".pdf",
        tocSubLevel = 4,
        dotsize = 0.5
)
    
 

plotListDF <- resList$plotListDF
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount
Obio@dataTableList[["DF_resultlist"]] <- resList$addList
        
## Done create cellRanger QC plots                                           ##
###############################################################################

if (length(plotListDF) > 3){
    tabVar <- "### Plot Per Sample Doublet Estimate .tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- "### Plot Per Sample Doublet Estimate .tabset .tabset-fade .tabset-pills"
}


```

{`r tabVar`}

```{r Plot_DF, echo=runDoubletFinder, eval=runDoubletFinder, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```


```{r UMAP_percentage, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##

resList <- doUMAP_plot_percMT(
    SampleList,
    obj =  Obio,
    figureCount = figureCount,
    VersionPdfExt = ".pdf",
    tocSubLevel = 4,
    dotsize = 0.5
)
 

plotListUMT <- resList$plotListUMT
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount

        
## Done create cellRanger QC plots                                           ##
###############################################################################

if (length(plotListUMT) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}


```

### Plot Per Sample MT Percentage {`r tabVar`}

```{r Plot_percent_MT, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```


```{r UMAP_nFeatures, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots                                                       ##

resList <- doUMAP_plot_nFeatRNA(
    SampleList,
    obj =  Obio,
    figureCount = figureCount,
    VersionPdfExt = ".pdf",
    tocSubLevel = 4,
    dotsize = 0.5
)
 

plotListNC <- resList$plotListNC
chnkVec <- resList$chnkVec
figureCount <- resList$figureCount

        
## Done create cellRanger QC plots                                           ##
###############################################################################

if (length(plotListNC) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}


```

### Plot Per Sample nFeatures RNA {`r tabVar`}

```{r Plot_nFeatureRNA, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"} 

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```


