<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r partB_pca_plots, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "B5.pca.plots."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```



```{r partB_create_PCA_plots, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Perform integrated analysis                                               ##

if (length(Obio@sampleDetailList) > 1){
  Seurat::DefaultAssay(OsC) <- "integrated"
} else {
  Obio@parameterList$singleCellClusterString <- gsub("integrated", "RNA", Obio@parameterList$singleCellClusterString)
  Seurat::DefaultAssay(OsC) <- "RNA"
}


# Run the standard workflow for visualization and clustering
## This will scale on the most variable features only
OsC <- Seurat::ScaleData(OsC, verbose = FALSE)

OsC <- Seurat::RunPCA(
  OsC, 
  npcs = Obio@parameterList$singleCellSeuratNpcs4PCA, verbose = FALSE
)
# t-SNE and Clustering

## Add PCA clusters to data collection ##


OsC <- Seurat::RunUMAP(OsC, reduction = "pca", dims = 1:Obio@parameterList$singleCellSeuratNpcs4PCA)

OsC <- Seurat::RunTSNE(OsC, reduction = "pca", dims = 1:Obio@parameterList$singleCellSeuratNpcs4PCA)

OsC <- Seurat::FindNeighbors(OsC, reduction = "pca", dims = 1:Obio@parameterList$singleCellSeuratNpcs4PCA)

OsC <- Seurat::FindClusters(OsC, resolution = Obio@parameterList$singleCellClusterParameter)

## Rational: Run PCA on variable features, then scale data for heatmaps and other applications

if (length(Obio@sampleDetailList) > 1){
  Seurat::DefaultAssay(OsC) <- Obio@parameterList$scIntegrationMethod
  allGenes <- rownames(x = OsC@assays[[Obio@parameterList$scIntegrationMethod]])
  OsC <- Seurat::ScaleData(OsC, verbose = FALSE, features=allGenes)
} 

Seurat::DefaultAssay(OsC) <- "RNA"
allGenes <- rownames(x = OsC@assays$RNA)
OsC <- Seurat::ScaleData(OsC, verbose = FALSE, features=allGenes)


###############################################################################
## Add custom cluster annotation if specified                                ##
FNcol <- paste0(cwd, "/design/customClusterAnnotation.txt")
tableValid <- FALSE

if (file.exists(FNcol)){
  dfClusterAnnotation <- read.delim(
    FNcol, 
    header = T, 
    sep = "\t",
    stringsAsFactors = F
  )
  
  ## Check column names ##
  pos1 <- grep("seurat_clusters", names(dfClusterAnnotation))
  pos2 <- grep("clusterName", names(dfClusterAnnotation))
  pos3 <- grep("clusterColor", names(dfClusterAnnotation))
  
  ## Check if clusters match ##
  inClust <- unique(as.character(dfClusterAnnotation$seurat_clusters))
  oClust <- unique(as.character(OsC@meta.data$seurat_clusters))
  
  
  if (length(pos1) != 0 & length(pos2) != 0 & length(pos3) != 0 ){
    ## Remove spaces ##
    dfClusterAnnotation$clusterName <- gsub(" ", "_", dfClusterAnnotation$clusterName)
    dfClusterAnnotation$clusterName <- gsub("\\.", "_", dfClusterAnnotation$clusterName)
    dfClusterAnnotation$clusterName <- gsub("-", "_", dfClusterAnnotation$clusterName)
    dfClusterAnnotation$clusterName <- gsub("__", "_", dfClusterAnnotation$clusterName)
    dfClusterAnnotation$clusterName <- gsub("_$", "", dfClusterAnnotation$clusterName)
    ## Check if clusters match ##
    inClust <- unique(as.character(dfClusterAnnotation$seurat_clusters))
    oClust <- unique(as.character(OsC@meta.data$seurat_clusters))
    if (length(inClust) == length(intersect(inClust, oClust))){
      tableValid <- TRUE
    } else {
      tableValid <- FALSE
    }
    
  } else {
    tableValid <- FALSE
  }
}

if (!file.exists(FNcol) | !tableValid){
  dfClusterAnnotation <- OsC@meta.data[,c("cellID", "seurat_clusters")]
  
  levels <- as.vector(sort(unique(dfClusterAnnotation$seurat_clusters)))
  clusterOrder <- as.numeric(sort(unique(dfClusterAnnotation$seurat_clusters)))
  
  library(scales)
  clusterCols <- hue_pal()(length(levels))
  
  dfClusterAnnotation <- data.frame(
    seurat_clusters = levels,
    clusterName = paste0("C", levels),
    clusterColor = clusterCols,
    clusterOrder = clusterOrder,
    stringsAsFactors = F
  )
  
  #row.names(dfClusterAnnotation) <- dfClusterAnnotation$cellID
  #dfClusterAnnotation$cellID <- NULL
  ## Add sample colors ##
  
  annoDir <- paste0(cwd, "/design")
  
  if (!dir.exists(annoDir)){
    dir.create(annoDir)
  }
  
  
  
  
  FNcol <- paste0(annoDir, "/clusterAnnotation.txt")
  write.table(
    dfClusterAnnotation,
    FNcol,
    row.names=F,
    sep = "\t"
  ) 
}

## Make sure dfClusterAnnotation has a clusterOrder column
pos <- grep("^clusterOrder$", names(dfClusterAnnotation))

if (length(pos) ==1){
  dfClusterAnnotation <- dfClusterAnnotation[order(dfClusterAnnotation$clusterOrder, decreasing = F),]
  orderVec <- dfClusterAnnotation$clusterName
  Obio@parameterList[["clusterNameOrder"]] <- orderVec
} else {
  ###############################################################################
  ## Order average expression by cluster similarity (most variable genes)      ##
  assay <- NULL
  assay <- assay %||% DefaultAssay(object = OsC)
  
  
  features <- VariableFeatures(object = OsC)
  features <- intersect(x = features, y = rownames(x = OsC))
  data.avg <- AverageExpression(object = OsC, assays = assay, 
                                features = features, slot = "data", verbose = T)[[1]]
  
  
  
  if (ncol(data.avg) > 1){
    data.dist <- dist(x = t(x = data.avg[features, ]))
    dforder <- hclust(d = data.dist)
    orderVec <- names(dfAvgExpr)[dforder$order]
  } else {
    orderVec <- names(data.avg)
  }
  
  Obio@parameterList[["clusterNameOrder"]] <- orderVec
  
}

###############################################################################
## Merge into OsC@meta.data                                                  ##

dfAdd <- OsC@meta.data[,c("seurat_clusters", "cellID")]
dfAdd$seurat_clusters <- as.character(dfAdd$seurat_clusters)
dfClusterAnnotation$seurat_clusters <- as.character(dfClusterAnnotation$seurat_clusters)

dfClusterAnnotation$clusterOrder <- NULL

dfAdd <- merge(
  dfAdd,
  dfClusterAnnotation,
  by.x = "seurat_clusters",
  by.y = "seurat_clusters"
)

dfAdd <- data.frame(dfAdd, stringsAsFactors = F)

row.names(dfAdd) <- dfAdd$cellID
dfAdd$cellID <- NULL
dfAdd$seurat_clusters <- NULL

OsC <- addDf2seuratMetaData(
  obj = OsC, 
  dfAdd = dfAdd
)

Seurat::Idents(OsC) <- "clusterName"
Seurat::Idents(OsC) <- factor(Seurat::Idents(OsC), levels = Obio@parameterList[["clusterNameOrder"]])
#OsC@meta.data$seurat_clusters <- factor(OsC@meta.data$seurat_clusters, levels = c(unique(as.numeric(dfClusterAnnotation$seurat_clusters))))

## Done                                                                      ##
###############################################################################

###############################################################################
## Add custom sample annotation if specified                                 ##
FNsample <- paste0(cwd, "/design/customSampleAnnotation.txt")
tableValid <- FALSE

if (file.exists(FNsample)){
  dfSampleAnnotation <- read.delim(
    FNsample, 
    header = T, 
    sep = "\t",
    stringsAsFactors = F
  )
  
  ## Check column names ##
  pos1 <- grep("sampleID", names(dfSampleAnnotation))
  pos2 <- grep("sampleName", names(dfSampleAnnotation))
  pos3 <- grep("sampleColor", names(dfSampleAnnotation))
  
  
  if (length(pos1) != 0 & length(pos2) != 0 & length(pos3) != 0){
    ## Edit sample annotation ##
    dfSampleAnnotation$sampleName <- gsub(" ", "_", dfSampleAnnotation$sampleName)
    dfSampleAnnotation$sampleName <- gsub("\\.", "_", dfSampleAnnotation$sampleName)
    dfSampleAnnotation$sampleName <- gsub("-", "_", dfSampleAnnotation$sampleName)
    dfSampleAnnotation$sampleName <- gsub("__", "_", dfSampleAnnotation$sampleName)
    dfSampleAnnotation$sampleName <- gsub("_$", "", dfSampleAnnotation$sampleName)
    ## Check if clusters match ##
    inClust <- unique(as.vector(dfSampleAnnotation$sampleID))
    oClust <- unique(as.vector(OsC@meta.data$sampleID))
    if (length(inClust) == length(intersect(inClust, oClust))){
      tableValid <- TRUE
    } else {
      tableValid <- FALSE
    }  
  } else {
    tableValid <- FALSE
  }
}

if (!file.exists(FNsample) | !tableValid){
  dfSampleAnnotation <- OsC@meta.data[,c("cellID", "sampleID")]
  
  levels <- sort(unique(dfSampleAnnotation$sampleID))
  
  library(scales)
  sampleCols <- hue_pal()(length(levels))
  
  dfSampleAnnotation <- data.frame(
    sampleID = levels,
    sampleName = levels,
    sampleColor = sampleCols
  )
  
  #row.names(dfSampleAnnotation) <- dfSampleAnnotation$cellID
  #dfClusterAnnotation$cellID <- NULL
  ## Add sample colors ##
  annoDir <- paste0(cwd, "/design")
  
  if (!dir.exists(annoDir)){
    dir.create(annoDir)
  }
  
  FNsample <- paste0(annoDir, "/sampleAnnotation.txt")
  
  
  write.table(
    dfSampleAnnotation,
    FNsample,
    row.names=F,
    sep = "\t"
  ) 
}


###############################################################################
## Merge into OsC@meta.data                                                  ##

dfAdd <- OsC@meta.data[,c("cellID", "sampleID")]
row.names(dfAdd) <- dfAdd$cellID

dfAdd <- merge(
  dfAdd,
  dfSampleAnnotation,
  by.x = "sampleID",
  by.y = "sampleID"
)

row.names(dfAdd) <- dfAdd$cellID
dfAdd$cellID <- NULL
dfAdd$sampleID <- NULL

OsC <- addDf2seuratMetaData(
  obj = OsC, 
  dfAdd = dfAdd
)


## Done                                                                      ##
###############################################################################


###############################################################################
## Find all markers                                                          ##
Seurat::DefaultAssay(OsC) <- "RNA"
Seurat::Idents(OsC) <- "clusterName"

lgFCthreshold <- 0.25

dfGeneralMarkers <- Seurat::FindAllMarkers(
  object = OsC, 
  only.pos = FALSE, 
  min.pct = 0.1, 
  logfc.threshold = lgFCthreshold,
  test.use = "roc",
  assay =  "RNA",
  slot = "data"
)

if (nrow(dfGeneralMarkers) == 0 | length(unique(dfGeneralMarkers$cluster)) < 2){
  lgFCthreshold <- 0.00
  dfGeneralMarkers <- Seurat::FindAllMarkers(
    object = OsC, 
    only.pos = FALSE, 
    min.pct = 0.01, 
    logfc.threshold = lgFCthreshold,
    test.use = "roc",
    assay =  "RNA",
    slot = "data"
  )
}

if (nrow(dfGeneralMarkers) > 0 & length(unique(dfGeneralMarkers$cluster)) >  2){
  dfGeneralMarkers[["direction"]] <- ""
  dfGeneralMarkers[dfGeneralMarkers$avg_diff >= 0, "direction"] <- "positive"
  dfGeneralMarkers[dfGeneralMarkers$avg_diff < 0, "direction"] <- "negative"
  
  Obio@dataTableList[["dfGeneralMarkers"]] <- data.frame(NULL)
  Obio@dataTableList[["dfGeneralMarkers"]] <- dfGeneralMarkers
  
  dfGeneralMarkersFilt <- dfGeneralMarkers[dfGeneralMarkers$avg_diff > lgFCthreshold | dfGeneralMarkers$avg_diff < -lgFCthreshold,]
  
  Obio@dataTableList[["dfGeneralMarkersFilt"]] <- data.frame(NULL)
  Obio@dataTableList[["dfGeneralMarkersFilt"]] <- dfGeneralMarkersFilt
  
  dfGeneralMarkersPos <- dfGeneralMarkers[dfGeneralMarkers$direction == "positive", ]
  dfTop1 <- data.frame(dfGeneralMarkersPos %>% group_by(cluster) %>% top_n(1, avg_diff))
  dfTop5 <- data.frame(dfGeneralMarkersPos %>% group_by(cluster) %>% top_n(5, avg_diff))
  dfTop10 <- data.frame(dfGeneralMarkersPos %>% group_by(cluster) %>% top_n(10, avg_diff))
  dfTop50 <- data.frame(dfGeneralMarkersPos %>% group_by(cluster) %>% top_n(50, avg_diff))
  
  Obio@dataTableList[["dfGeneralMarkersTop10"]] <- dfTop10
  
  Obio@dataTableList$referenceList[["Top10clusterMarkers"]] <- as.vector(
    unique(
      dfTop10$gene
    )
  )
}
  ````