<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r partB_retrieve_reference_gene_sets_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "B2.ref.gmt."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```


# Load Reference Gene Sets
```{r partB_create_sample_list, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Load reference datasets                                                   ##
if (is.null(Obio@dbDetailList[["db.pwd"]])){
    ###############################################################################
    ## Set db access credentials                                                 ##
    if (dir.exists("/Volumes/babs/working/boeings/")){
        hpc.mount <- "/Volumes/babs/working/boeings/"
    } else if (dir.exists("Y:/working/boeings/")){
        hpc.mount <- "Y:/working/boeings/"
    } else if (dir.exists("/camp/stp/babs/working/boeings/")){
        hpc.mount <- "/camp/stp/babs/working/boeings/"
    } else {
        hpc.mount <- ""
    }
  
    ## Loading the BABS password ##
    FN <- paste0(hpc.mount, "Projects/reference_data/pwd_folder/babs.txt")
    dbTable <- read.delim(
      FN,
      header = F,
      sep = "\t",
      stringsAsFactors = F
    )
    
    db.pwd <- as.vector(dbTable[1,1])
    
    
    ## Done                                                                      ##
    ###############################################################################
    
    Obio@dbDetailList[["db.pwd"]] <- db.pwd
}

Obio@dataTableList[["referenceList"]] <- NULL

if (!is.null(Obio@dbDetailList$host)){
  
    if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol" 
  } else {
            queryGS <- Obio@parameterList$geneIDcolumn
  }
  
    Obio@dataTableList[["referenceList"]] <- list(
        "s.genes" = retrieve.gene.category.from.db(
                        cat_id = "ag_lab_categories__41",
                        password = Obio@dbDetailList[["db.pwd"]],
                        gene.symbol = queryGS,
                        user = Obio@dbDetailList$db.user,
                        host = Obio@dbDetailList$host
                    ),
        "g2m.genes" = retrieve.gene.category.from.db(
                          cat_id = "ag_lab_categories__42",
                          password = Obio@dbDetailList[["db.pwd"]],
                          gene.symbol = queryGS,
                          user = Obio@dbDetailList$db.user,
                          host = Obio@dbDetailList$host
                    ),
        "TFs" = retrieve.gene.category.from.db(
                          cat_id = "ag_lab_categories__10",
                          password = Obio@dbDetailList[["db.pwd"]],
                          gene.symbol = queryGS,
                          user = Obio@dbDetailList$db.user,
                          host = Obio@dbDetailList$host
                    )
        
      )
}




## Done create cellRanger QC plots                                           ##
###############################################################################


```


